# Generated by Django 3.0.5 on 2020-05-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KV_login', models.CharField(max_length=30)),
                ('KV_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveSmallIntegerField()),
                ('question_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_date', models.DateField(auto_now=True)),
                ('KV_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claim.KV')),
                ('question_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claim.Question')),
            ],
        ),
    ]
