# Generated by Django 3.0.5 on 2020-05-31 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='KV_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claim.KV', to_field='KV_name'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='question_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claim.Question', to_field='question_number'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='default', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='kv',
            name='KV_name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
