# Generated by Django 3.0.5 on 2020-05-31 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_auto_20200531_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='kv',
            name='group_name',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='claim.Group', to_field='group_name'),
        ),
    ]
