# Generated by Django 3.0.5 on 2020-06-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0005_auto_20200607_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='error_date',
            field=models.DateField(),
        ),
    ]
