# Generated by Django 3.0.5 on 2020-07-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0007_captain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captain',
            old_name='kv_name',
            new_name='KV_name',
        ),
    ]
