# Generated by Django 3.0.5 on 2020-07-10 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0008_auto_20200710_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='question_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claim.Question'),
        ),
    ]
