# Generated by Django 3.0.5 on 2020-11-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0009_auto_20200710_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='form_id',
            field=models.IntegerField(default=100),
        ),
    ]
